.\" Manpage for copyko.
.\" Contact oks-mgn@mail.ru to correct errors or typos.
.TH COPYKO 1 "23 сентября 2019" "0.2" "copyko man page"
.SH ИМЯ
copyko \- копирует модули ядра и их зависимости
.SH ИСПОЛЬЗОВАНИЕ
.B copyko
[\fIОПЦИИ\fR] \fIмодуль\fR ... \fIкуда\fR
.SH ОПИСАНИЕ
.B copyko
копирует модули ядра (файлы с расширением ".ko") из исходной папки а целевую.
Программа разрабатывалась для использования при создании загрузочных CD-дисков.
Если модуль зависит от других, они тоже будут скопированы, и их зависимости будут скопированы рекурсивно.
Структура каталогов при копировании сохраняется, модули помещаются в те же подкаталоги целевого каталога, где были в исходном каталоге.
Также копируются файлы прошивок (firmware), указанные в зависимостях.
Программа не перезаписывает существующие файлы.
\fBcopyko\fR использует программу \fBmodinfo\fR чтобы прочитать информацию о зависимостях модулей.
.TP
\fIмодуль\fR
имя файла без расширения.
.TP
\fIкуда\fR
целевой каталог.
.SH ОПЦИИ
Обязательные аргументы для длинных опций обязательны и для коротких.
.TP
\fB\-f\fR, \fB--from\fR=\fIОТКУДА\fR
каталог, в котором искать модули, например /lib/modules/5.1.0-rc7.
По умолчанию используется каталог с модулями текущей версии ядра.
.TP
\fB--fwsrc\fR=\fIОТКУДА\fR
каталог с прошивками, например /lib/firmware.
По умолчанию $(--from)/../../firmware
.TP
\fB--fwdsr\fR=\fIКУДА\fR
целевой каталог для копирования прошивок, например mydir/lib/firmware.
По умолчанию $(destination)/../../firmware
.TP
\fB\-l\fR, \fB--link\fR
пытаться делать жесткие ссылки на файлы, а не копировать их.
Это ускорит работу с сэкономит место на диске.
При ошибках отображается только первая, чтобы не замусоривать экран.
.TP
\fB\-v\fR, \fB--verbose\fR
показывать выполняемые действия и дополнительную информацию.
Например, если вы копируете модули \fIa\fR и \fIb\fR, при этом модуль \fIa\fR зависит от \fIb\fR, программа предупредит Вас, что достаточно указать для копирования только модуль \fIa\fR.
Модуль \fIb\fR сокпируется автоматически как зависимость.
.TP
\fB--help\fR
отобразить краткую справку.
.TP
\fB--version\fR
показать версию программы.
.SH УСЛОВИЯ РАБОТЫ
Модули не должны иметь бесконечных циклов зависимостей.
Дерево зависимостей в программе ограничено значением 1024.
.PP
Имена файлов не должны содержать пробелы и запятые.
Расширение файла у модуля должно быть ".ko".
.PP
В подкаталогах источника не должно быть нескольких файлов с одним и тем же именем.
.PP
Модули расположены в каталоге источника, не за его пределами, символьные ссылки не используются, работа с ними не продумывалась.
.PP
Все исходные подкаталоги доступны для чтения.
Программа молча пропускает каталоги, которые не может прочитать.
.SH ПРИМЕР
copyko fuse isofs udf my_livecd/modules/5.1.0-rc7
.SH СМОТРИ ТАЖ КЕ
modinfo(8)
.SH ОШИБКИ
Нет известных.
.SH АВТОР
Oshepkov Konstantin (oks-mgn@mail.ru)
